<a href="https://colab.research.google.com/github/andresfmolinas-cyber/analiticadedatosuq/blob/main/PARCIAL_1_ELECTIVA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
# #Importando las librerias necesarias para el analisis de la GEIH
import pandas as pd
import numpy as np

In [29]:
#Leyendo los datos de la geih
df_cgsse = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/cgsse.CSV'
                       ,encoding='latin',sep=';'
                       )

df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )

df_d = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/No%20ocupados.CSV'
                       ,encoding='latin',sep=';'
                       )
df_ft = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'
                       ,encoding='latin',sep=';'
                       )

/tmp/ipykernel_483/669951302.py:6: DtypeWarning: Columns (28,89,133,147,158) have mixed types. Specify dtype option on import or set low_memory=False.
  df_o = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Ocupados.CSV'
/tmp/ipykernel_483/669951302.py:13: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ft = pd.read_csv('https://github.com/niconomist98/DataAnalyticsUQ/raw/refs/heads/main/Datos/GEIH2025/Fuerza%20de%20trabajo.CSV'

In [30]:
df_cgsse.columns

Index(['PERIODO', 'MES', 'PER', 'DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'HOGAR',
       'REGIS', 'AREA', 'CLASE', 'FEX_C18', 'DPTO', 'PT', 'P6016', 'P3271',
       'P6040', 'P6030S1', 'P6030S3', 'P6050', 'P6083', 'P6083S1', 'P6081',
       'P6081S1', 'P2057', 'P2059', 'P2061', 'P6080', 'P6080S1', 'P6080S1A1',
       'P6070', 'P6071', 'P6071S1', 'P6090', 'P6100', 'P6110', 'P6120',
       'P1906S1', 'P1906S2', 'P1906S3', 'P1906S4', 'P1906S5', 'P1906S6',
       'P1906S7', 'P1906S8', 'P6160', 'P6170', 'P3041', 'P3042', 'P3042S1',
       'P3042S2', 'P3043', 'P3043S1', 'P3038', 'P3039', 'POB_MAY18'],
      dtype='object')

In [31]:
df_cgsse.head()

,PERIODO,MES,PER,DIRECTORIO,SECUENCIA_P,ORDEN,HOGAR,REGIS,AREA,CLASE,...,P6170,P3041,P3042,P3042S1,P3042S2,P3043,P3043S1,P3038,P3039,POB_MAY18
0,20250626,6,2025,8238974,1,1,1,10,NaN,2,...,2.0,NaN,5.0,2.0,NaN,2.0,NaN,1.0,2.0,1.0
1,20250626,6,2025,8238974,1,2,1,10,NaN,2,...,2.0,NaN,5.0,1.0,NaN,1.0,NaN,2.0,1.0,1.0
2,20250626,6,2025,8238975,1,1,1,10,NaN,2,...,2.0,NaN,3.0,3.0,NaN,NaN,NaN,2.0,1.0,1.0
3,20250626,6,2025,8238975,1,2,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,2.0,1.0,1.0
4,20250626,6,2025,8238975,1,3,1,10,NaN,2,...,2.0,NaN,1.0,0.0,NaN,NaN,NaN,1.0,2.0,1.0

In [32]:
# PREGUNTA 1 DEL PARCIAL
# POBLACION TOTAL
PT =  df_cgsse['FEX_C18'].sum()
print(f' La población total de referencia para Colombia basado en el modulo cgsse de la GEIH y el factor de expansión es {PT}')

 La población total de referencia para Colombia basado en el modulo cgsse de la GEIH y el factor de expansión es 52045001.000009045

In [33]:
# POBLACION EN EDAD DE TRABAJAR
PET = df_cgsse[df_cgsse['P6040']>=15]['FEX_C18'].sum()
print(f'Poblacion en edad de trabajar: {PET}')

Poblacion en edad de trabajar: 40653416.00000409

In [34]:
# POBLACION QUE NO ESTA EN EDAD DE TRABAJAR
PNET = df_cgsse[df_cgsse['P6040']<15]['FEX_C18'].sum()
print(f'Poblacion que no está en  edad de trabajar: {int(PNET)}')

Poblacion que no está en  edad de trabajar: 11391585

In [35]:
# POBLACION ECONOMICAMENTE ACTIVA E INACTIVA
PEA = df_ft[df_ft['FT']==1]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa: {PEA}')

PEI = df_ft[df_ft['FFT']==1]['FEX_C18'].sum()
print(f'Poblacion Economicamente inactiva: {int(PEI)}')

Poblacion Economicamente Activa: 25974846.223567855
Poblacion Economicamente inactiva: 14678569

In [36]:
# TASA DE OCUPACION
O = df_o['FEX_C18'].sum()
print(f'Poblacion ocupada: {int(O)}')

PET = df_ft['FEX_C18'].sum()
print(f'Poblacion En edad de trabajar : {int(PET)}')

TO = O/PET
print(f'Tasa de Ocupacion: {TO:.2%}')

Poblacion ocupada: 23752952
Poblacion En edad de trabajar : 40653416
Tasa de Ocupacion: 58.43%

In [37]:
# TASA DE DESEMPLEO
D = df_d[df_d['DSI']==1]['FEX_C18'].sum()
print(f'Poblacion Desempleada: {D}')

TD = D/PEA
print(f'Tasa de Desempleo: {TD*100}%')

# Justificación:Se calcularon indicadores como la población total, la población en edad de trabajar, la población económicamente activa e inactiva, así como las tasas de ocupación y desempleo, con el fin de analizar la situación del mercado laboral.

#Explicación:Primero se identifica la población total y se clasifica según la edad para obtener la población en edad de trabajar. Luego se divide entre población activa (ocupados y desempleados) e inactiva. Con estos datos se calculan las tasas de ocupación y desempleo.

#Interpretación:Estos indicadores permiten entender cómo se distribuye la población frente al trabajo y evaluar el nivel de participación laboral y las condiciones de empleo.

Poblacion Desempleada: 2221893.563312005
Tasa de Desempleo: 8.554020086155527%

In [38]:
df_ft['DPTO'].unique()

array([ 8, 70, 41, 63, 66,  5, 11, 13, 15, 17, 18, 19, 20, 23, 25, 27, 44,
       47, 50, 52, 54, 68, 73, 76, 81, 85, 86, 88, 91, 94, 95, 97, 99])

PREGUNTA 2 DEL PARCIAL

In [39]:
# CALCULAR LA TASA DE DESEMPLEO PARA HOMBRES Y MUJERES EN RISARALDA, CALDAS, TOLIMA Y QUINDIO ¿ CUAL ES EL DEPARTAMENTO CON MAYOR Y MENOS TASA DE DESEMPLEO?
# SE ANEXA TABLA DE
df_d = pd.merge(df_d, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']],
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

df_ft = pd.merge(df_ft, df_cgsse[['DIRECTORIO', 'SECUENCIA_P', 'ORDEN', 'P3271','P6040']],
                        on=['DIRECTORIO', 'SECUENCIA_P', 'ORDEN'], how='left')

In [40]:
# 1. Calcular cantidad de hombres desempleados en el quindío
HDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==63) & (df_d['P3271']==1)]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Quindio: {HDQ}')

# 2. Calcular cantidad de hombres en la PEA del quindío
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==1) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el quindío: {PEAHQ}')

# 3. Calcular la tasa de desempleo en hombres del quindío
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del quindío: {TDHQ*100}%')

Hombres Desempleados en el Quindio: 17869.520960767004
Poblacion Economicamente Activa de hombres en el quindío: 174625.87195169798
Tasa de Desempleo en hombres del quindío: 10.233031773040919%

In [41]:
# 1. Calcular cantidad de MUJERES desempleadas en el quindío
MDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==63) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Mujeres Desempleadas en el Quindio: {MDQ}')

# 2. Calcular cantidad de mujeres en la PEA del quindío
PEAMQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de mujeres en el quindío: {PEAMQ}')

# 3. Calcular la tasa de desempleo en mujeres del quindío
TDMQ = MDQ/PEAMQ
print(f'Tasa de Desempleo en mujeres del quindío: {TDMQ*100}%')

Mujeres Desempleadas en el Quindio: 10618.534945967001
Poblacion Economicamente Activa de mujeres en el quindío: 116885.879263648
Tasa de Desempleo en mujeres del quindío: 9.084531863781265%

In [42]:
# 1. Calcular cantidad de hombres desempleados en Risaralda
HDR = df_d[(df_d['DSI']==1) & (df_d['DPTO']==66) & (df_d['P3271']==2)]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Risaralda: {HDR}')

# 2. Calcular cantidad de hombres en la PEA Risaralda
PEAHR = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==66) & (df_ft['P3271']==2) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el Risaralda: {PEAHR}')

# 3. Calcular la tasa de desempleo en hombres de Risaralda
TDHR = HDR/PEAHR
print(f'Tasa de Desempleo en hombres del Risaralda: {TDHR*100}%')

Hombres Desempleados en el Risaralda: 21676.799766712
Poblacion Economicamente Activa de hombres en el Risaralda: 203157.903399127
Tasa de Desempleo en hombres del Risaralda: 10.669926891362644%

PREGUNTA 3 DEL PARCIAL

In [43]:
#Segmento de 18 a 24 años de edad

# 1. Calcular cantidad personas desempleadas entre los 18 - 24
D1824 = df_d[(df_d['DSI']==1) & (df_d['P6040']>=18) & (df_d['P6040']<=24) & (df_d['DPTO']==63)]['FEX_C18'].sum()
print(f'Personas Desempleadas en el quindío entre los 18 - 24 años: {D1824}')

# 2. Calcular cantidad personas en la PEA entre los 18 - 24
PEA1824 = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=18) & (df_ft['P6040']<=24) & (df_ft['DPTO']==63)]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa en el quindío entre los 18 - 24 años: {PEA1824}')

# 3. Calcular la tasa de desempleo en personas entre los 18 - 24 del quindío
TD1824 = D1824/PEA1824
print(f'Tasa de Desempleo en personas entre los 18 - 24 del quindío: {TD1824*100}%')

Personas Desempleadas en el quindío entre los 18 - 24 años: 3819.2724449800003
Poblacion Economicamente Activa en el quindío entre los 18 - 24 años: 29912.663758397
Tasa de Desempleo en personas entre los 18 - 24 del quindío: 12.768078683423386%

In [44]:
q = [[63,18,24],[63,24,30],[63,30,40],[63,40,50],[63,60,150]]
c = [[17,18,24],[17,24,30],[17,30,40],[17,40,50],[17,60,150]]
r = [[66,18,24],[66,24,30],[66,30,40],[66,40,50],[66,60,150]]

for a,b,c in c:

    # 1. Calcular cantidad personas desempleadas en el departamento a en el segmento entre b y c
    D = df_d[(df_d['DSI']==1) & (df_d['P6040']>=b) & (df_d['P6040']<=c) & (df_d['DPTO']==a)]['FEX_C18'].sum()
    print(f'Personas Desempleadas en {a} entre los {b} - {c} años: {D}')
    # 2. Calcular cantidad personas en la PEA en el departamento a en el segmento entre b y c
    PEA = df_ft[(df_ft['FT']==1) & (df_ft['P6040']>=b) & (df_ft['P6040']<=c) & (df_ft['DPTO']==a)]['FEX_C18'].sum()
    print(f'Poblacion Economicamente Activa en {a} entre los {b} - {c} años: {PEA}')
    # 3. Calcular la tasa de desempleo en el departamento a en el segmento entre b y c
    TD = D/PEA
    print(f'Tasa de Desempleo en personas entre los {b} - {c} en {a}: {TD*100}%')

Personas Desempleadas en 17 entre los 18 - 24 años: 6259.083688154001
Poblacion Economicamente Activa en 17 entre los 18 - 24 años: 66978.254075637
Tasa de Desempleo en personas entre los 18 - 24 en 17: 9.344949005517167%
Personas Desempleadas en 17 entre los 24 - 30 años: 6090.488353998
Poblacion Economicamente Activa en 17 entre los 24 - 30 años: 94541.70353229
Tasa de Desempleo en personas entre los 24 - 30 en 17: 6.442118267858205%
Personas Desempleadas en 17 entre los 30 - 40 años: 7691.5534119310005
Poblacion Economicamente Activa en 17 entre los 30 - 40 años: 134487.41843531598
Tasa de Desempleo en personas entre los 30 - 40 en 17: 5.719162060970324%
Personas Desempleadas en 17 entre los 40 - 50 años: 6318.584371157001
Poblacion Economicamente Activa en 17 entre los 40 - 50 años: 123334.19349942802
Tasa de Desempleo en personas entre los 40 - 50 en 17: 5.123140786732679%
Personas Desempleadas en 17 entre los 60 - 150 años: 2543.690331052
Poblacion Economicamente Activa en 17 entre los 60 - 150 años: 62637.207145629
Tasa de Desempleo en personas entre los 60 - 150 en 17: 4.060989381499756%

In [45]:
# 1. Calcular  desempleados en el quindío
HDQ = df_d[(df_d['DSI']==1) & (df_d['DPTO']==63) ]['FEX_C18'].sum()
print(f'Hombres Desempleados en el Quindio: {HDQ}')

# 2. Calcular cantidad de hombres en la PEA del quindío
PEAHQ = df_ft[(df_ft['FT']==1) & (df_ft['DPTO']==63) ]['FEX_C18'].sum()
print(f'Poblacion Economicamente Activa de hombres en el quindío: {PEAHQ}')

# 3. Calcular la tasa de desempleo en hombres del quindío
TDHQ = HDQ/PEAHQ
print(f'Tasa de Desempleo en hombres del quindío: {TDHQ*100}%')

Hombres Desempleados en el Quindio: 28488.055906734
Poblacion Economicamente Activa de hombres en el quindío: 291511.75121534604
Tasa de Desempleo en hombres del quindío: 9.772524019345367%

In [47]:
desem = df_d[(df_d['DSI']==1) & (df_d['P3271']==2) &  (df_d['P6040']>=18) & (df_d['P6040']<25) ].groupby('DPTO')['FEX_C18'].sum()

persona_activa = df_ft[(df_ft['FT']==1)  & (df_ft['P3271']==2) &  (df_ft['P6040']>=18) & (df_ft['P6040']<25)].groupby('DPTO')['FEX_C18'].sum()

resultado=pd.DataFrame({'PEA': persona_activa, 'DESEMPLEADO': desem})

resultado['tasa_desempleo(%)']=(resultado['DESEMPLEADO']/resultado['PEA']) *100

resultado= resultado.sort_values(by='tasa_desempleo(%)', ascending=False)

departamentos = {
    17: 'CALDAS',
    73: 'TOLIMA',
    63: 'QUINDIO',
    66: 'RISARALDA',
}

resultado['Departamento'] = resultado.index.map(dpto_nombre)

resultado = resultado.sort_values(by='tasa_desempleo(%)', ascending=False)

print(resultado)

                PEA   DESEMPLEADO  tasa_desempleo(%) Departamento
DPTO
81      4557.559051   2577.533630          56.555134          NaN
23     52732.068435  28569.023578          54.177703          NaN
18      9144.913349   3884.182030          42.473689          NaN
47     17700.819667   7201.098152          40.682286          NaN
27      3945.587308   1567.732663          39.733823          NaN
54     31859.773898  11595.983315          36.396942          NaN
88       707.624818    250.784551          35.440327          NaN
8      69505.772374  22903.029524          32.951263          NaN
13     32709.829180  10174.459827          31.105206          NaN
85      5001.466703   1480.021594          29.591751          NaN
20     33599.506115   9663.245696          28.760083          NaN
68     50320.691707  14246.156038          28.310732          NaN
76    130755.217031  36109.934902          27.616439          NaN
70     22783.048779   6138.284033          26.942329          NaN
73     28935.757777   7272.960609          25.134854       TOLIMA
99       729.676863    182.135129          24.961067          NaN
94       149.199014     36.500334          24.464192          NaN
95      1855.296112    446.433322          24.062645          NaN
66     28126.786254   6650.117004          23.643359    RISARALDA
5     203216.886475  44665.007314          21.978984          NaN
86       377.735211     82.962391          21.963108          NaN
11    226575.252656  48269.008325          21.303742          NaN
44     31535.623339   6605.939740          20.947548          NaN
25    139786.866034  26168.257580          18.720112          NaN
52     44282.658545   7688.792588          17.362988          NaN
50     47340.868963   6976.482390          14.736701          NaN
17     24393.338292   2677.886106          10.977940       CALDAS
15     24491.024385   2464.555776          10.063098          NaN
41     19123.128493   1918.472193          10.032209          NaN
19     37817.442681   2965.201120           7.840829          NaN
63     10289.693612    654.189193           6.357713      QUINDIO
91       344.823595           NaN                NaN          NaN
97       154.739938           NaN                NaN          NaN

PREGUNTA 4

In [50]:
departamentos = {
    63: "Quindío",
    66: "Risaralda",
    17: "Caldas",
    73: "Tolima"
}

resultados = []

for codigo, nombre in departamentos.items():

    desem = df_d[(df_d["DPTO"]==codigo) &
                 (df_d["P3271"]==2) &
                 (df_d["P6040"]>=18) &
                 (df_d["P6040"]<=25) &
                 (df_d["DSI"]==1)]["FEX_C18"].sum()

    pea = df_ft[(df_ft["DPTO"]==codigo) &
                (df_ft["P3271"]==2) &
                (df_ft["P6040"]>=18) &
                (df_ft["P6040"]<=25) &
                (df_ft["FT"]==1)]["FEX_C18"].sum()

    tasa = desem/pea

    resultados.append([nombre,tasa])

tabla = pd.DataFrame(resultados,columns=["Departamento","Tasa_desempleo"])

tabla
#Justificación: Se calcula la tasa de desempleo para mujeres entre 18 y 25 años en los departamentos de Quindío, Risaralda, Caldas y Tolima. Para ello se divide el número de mujeres desempleadas entre la población económicamente activa femenina del mismo grupo de edad.

#Interpretación:El departamento con la menor tasa refleja mejores oportunidades laborales para las mujeres jóvenes, lo que puede indicar un mercado laboral más dinámico o mayor demanda de trabajo en ese territorio.

  Departamento  Tasa_desempleo
0      Quindío        0.074682
1    Risaralda        0.229928
2       Caldas        0.145001
3       Tolima        0.213781

In [51]:
tabla.loc[tabla["Tasa_desempleo"].idxmin()]

Departamento       Quindío
Tasa_desempleo    0.074682
Name: 0, dtype: object

PREGUNTA 5

In [52]:
pet_quindio = df_cgsse[(df_cgsse["DPTO"]==63) & (df_cgsse["P6040"]>=15)]

hombres = pet_quindio[pet_quindio["P3271"]==1]["FEX_C18"].sum()
mujeres = pet_quindio[pet_quindio["P3271"]==2]["FEX_C18"].sum()

print("Hombres en edad de trabajar:", hombres)
print("Mujeres en edad de trabajar:", mujeres)

Hombres en edad de trabajar: 247037.510834763
Mujeres en edad de trabajar: 261387.92755063402

In [53]:
poblacion_total_quindio = df_cgsse[df_cgsse["DPTO"]==63]["FEX_C18"].sum()

porcentaje = (hombres+mujeres)/poblacion_total_quindio *100

print("Porcentaje de la población total:", porcentaje)

#Justificación:Se identificó la población del Quindío con 15 años o más, que corresponde a la población en edad de trabajar. Luego se separó por sexo para conocer cuántos hombres y mujeres pertenecen a este grupo.

#Interpretación:Este resultado permite conocer la estructura de la población potencialmente activa del departamento y qué proporción representa dentro de la población total.

Porcentaje de la población total: 84.30639511079708

PREGUNTA 6

In [54]:
pet_tolima = df_cgsse[(df_cgsse["DPTO"]==73) &
                      (df_cgsse["P6040"]>=15)]["FEX_C18"].sum()

poblacion_tolima = df_cgsse[df_cgsse["DPTO"]==73]["FEX_C18"].sum()

porcentaje = pet_tolima/poblacion_tolima *100

print("Porcentaje de población en edad de trabajar en Tolima:", porcentaje)
# Justificación:Se calculó el número de personas de 15 años o más en Tolima y se comparó con la población total del departamento para obtener el porcentaje.

#Interpretación:Este indicador muestra qué proporción de la población tiene edad para participar en el mercado laboral, lo cual es clave para analizar el potencial de fuerza de trabajo del departamento.

Porcentaje de población en edad de trabajar en Tolima: 77.01034018103488

PREGUNTA 7

In [55]:
inactivos = df_ft[(df_ft["DPTO"]==66) &
                  (df_ft["FFT"]==1)]["FEX_C18"].sum()

pet_risaralda = df_ft[df_ft["DPTO"]==66]["FEX_C18"].sum()

porcentaje = inactivos/pet_risaralda *100

print("Porcentaje de población económicamente inactiva en Risaralda:", porcentaje)
# Justificación:Se identificó la población económicamente inactiva en Risaralda y se comparó con la población en edad de trabajar del departamento.

#Interpretación:Un mayor porcentaje de inactividad indica que una parte importante de la población no participa en el mercado laboral, ya sea por estudio, jubilación o dedicación al hogar.

Porcentaje de población económicamente inactiva en Risaralda: 39.981490952554736

PREGUNTA 8

In [56]:
desempleados = df_d[(df_d["DPTO"]==63) &
                    (df_d["P6040"]>=18) &
                    (df_d["P6040"]<=30) &
                    (df_d["DSI"]==1)]["FEX_C18"].sum()

print("Personas desempleadas en Quindío entre 18 y 30 años:", desempleados)
#Justificación:Se filtró la población del Quindío entre 18 y 30 años y se identificaron las personas que se encuentran en condición de desempleo.

#Interpretación:Este resultado permite observar la magnitud del desempleo juvenil en el departamento, lo cual es importante para analizar las dificultades de inserción laboral de los jóvenes.

Personas desempleadas en Quindío entre 18 y 30 años: 9479.632579867999

PREGUNTA 9